class CreateCountyHistoricalUsages < ActiveRecord::Migration
  def change
    create_table :county_historical_usages do |t|
      t.string :year
      t.string :name
      t.string :code
      t.string :state
      t.decimal :total_population
      t.decimal :served_population
      t.decimal :commercial_ground_withdrawals
      t.decimal :commercial_surface_withdrawals
      t.decimal :commercial_public_withdrawals
      t.decimal :commercial_total_use
      t.decimal :commercial_reclaimed_use
      t.decimal :industrial_ground_withdrawals
      t.decimal :industrial_surface_withdrawals
      t.decimal :industrial_public_withdrawals
      t.decimal :industrial_total_use
      t.decimal :industrial_reclaimed_use
      t.decimal :domestic_ground_withdrawals
      t.decimal :domestic_surface_withdrawals
      t.decimal :domestic_public_withdrawals
      t.decimal :domestic_total_use
      t.decimal :domestic_per_capita_self_supplied
      t.decimal :domestic_per_capita_public_supplied
      t.decimal :fossil_ground_withdrawals
      t.decimal :fossil_surface_withdrawals
      t.decimal :fossil_public_withdrawals
      t.decimal :fossil_total_use
      t.decimal :fossil_reclaimed_use
      t.decimal :geothermal_ground_withdrawals
      t.decimal :geothermal_surface_withdrawals
      t.decimal :geothermal_public_withdrawals
      t.decimal :geothermal_total_use
      t.decimal :geothermal_reclaimed_use
      t.decimal :nuclear_ground_withdrawals
      t.decimal :nuclear_surface_withdrawals
      t.decimal :nuclear_public_withdrawals
      t.decimal :nuclear_total_use
      t.decimal :nuclear_reclaimed_use
      t.decimal :total_thermoelectric_ground_withdrawals
      t.decimal :total_thermoelectric_surface_withdrawals
      t.decimal :total_thermoelectric_public_withdrawals
      t.decimal :total_thermoelectric_total_use
      t.decimal :total_thermoelectric_reclaimed_use
      t.decimal :mining_ground_withdrawals
      t.decimal :mining_surface_withdrawals
      t.decimal :mining_public_withdrawals
      t.decimal :mining_total_use
      t.decimal :mining_reclaimed_use
      t.decimal :livestock_ground_withdrawals
      t.decimal :livestock_surface_withdrawals
      t.decimal :livestock_public_withdrawals
      t.decimal :livestock_total_use
      t.decimal :aquaculture_ground_withdrawals
      t.decimal :aquaculture_surface_withdrawals
      t.decimal :aquaculture_public_withdrawals
      t.decimal :aquaculture_total_use
      t.decimal :crop_ground_withdrawals
      t.decimal :crop_surface_withdrawals
      t.decimal :crop_public_withdrawals
      t.decimal :crop_total_use
      t.decimal :crop_reclaimed_use
      t.decimal :golf_ground_withdrawals
      t.decimal :golf_surface_withdrawals
      t.decimal :golf_public_withdrawals
      t.decimal :golf_total_use
      t.decimal :golf_reclaimed_use
      t.decimal :total_public_reclaimed
      t.timestamps null: false
    end
  end
end
